spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka_example
    username: example
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

kafka:
  host: localhost:9092
  topics:
    demo-topic:
      topicName: demo-topic
      partitionCount: 1
      replicationFactor: 1
      retentionInMs: 604800000
      consumerGroup: demo-consumers